services:
    app.email_notification_subscriber:
        class: WebsiteBundle\Event\EmailNotificationSubscriber
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [ setContainer, [ "@service_container" ] ]
    app.retry_crawl_subscriber:
        class: WebsiteBundle\Event\RetryCrawlSubscriber
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [ setContainer, [ "@service_container" ] ]
